version: '3.8'

services:
  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: fastapi_app:latest
    env_file:
      - ./api/.env
    environment:
      - DB_HOST=db
    networks:
      - siem_network

  react:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=/api
        - REACT_APP_WS_BASE_URL=ws://localhost
    image: react_app:latest
    env_file:
      - ./app/.env
    volumes:
      - ./app/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi
    networks:
      - siem_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi
      - react
    networks:
      - siem_network

networks:
  siem_network:
    external: true
